DRM="*M"
DRM_RADEON = { value = " *M", comment = ["", "For r300 or r600"] }
DRM_AMDGPU = { value = " *M", comment = ["", "For radeonsi"] }
DRM_AMDGPU_SI="*"
DRM_AMDGPU_CIK="*"
DRM_AMD_DC="*"
DRM_NOUVEAU = { value = " *M", comment = ["", "For nouveau"] }
DRM_NOUVEAU_GSP_DEFAULT="*"
DRM_I915 = { value = " *M", comment = ["", "For i915, crocus, or iris"] }
DRM_XE = { value = " *M", comment = ["", "For iris"] }
DRM_XE_DISPLAY = "*"
DRM_XE_FORCE_PROBE = '*'
DRM_VMWGFX = { value = " *M", comment = ["", "For svga"] }
DRM_VGEM = { value = " *", comment = ["", "For llvmpipe or softpipe"] }
