MEDIA_SUPPORT='*M'
MEDIA_SUBDRV_AUTOSELECT='*'
MEDIA_CAMERA_SUPPORT='*'
MEDIA_USB_SUPPORT='* '

[USB_VIDEO_CLASS]
value = '*M '
comment = [
	'Most modern USB camera needs this.',
	'For other devices you need to figure it out yourself',
]
